### ISSUE TITLE
Abstract the transfer protocol, default to ics20-1

### ISSUE THREAD

**Issue by michaelfig** [Agoric/dapp-pegasus#2]
@dckc said:
> I guess my question applies at 2 layers:
>  1) what bits go over the wire?
>  2) can the network abstraction be implemented using some other bits on the wire?

@michaelfig said:
> @dckc so for 1, it's the ics20-1 JSON transfer protocol.  You've correctly interpreted that relying on that is the only baked-in assumption in the current Pegasus contract. 

More precisely, there are bits of code that have sprinklings of ics20-1, and a well-intentioned `switch` statement to add new protocols.  It would be much better to create a TransferProtocol abstraction and allow peggers to implement that instead (as I alluded to in the demo presentation).

I was mistaken in thinking that because the transfer must be JSONable (purely data), so did the transferProtocol.  Ocap design is gradually being hammered into me by virtuous folks like you and @erights, but I'm still new here. :smile:

Separating out the [ICS20](https://github.com/cosmos/ics/tree/master/spec/ics-020-fungible-token-transfer) reliance would imply something like:

```js
/**
 * @typedef {Object} TransferProtocol
 * @property {() => string} getAllegedName returns something like 'ics20-1'
 * @property {(endpointP: Endpoint|PromiseLike<string>, denom: string) => Promise<string>} makeDenomUri e.g. 'ics20-1:portID/channelID/denom'
 * @property {(localBrand: Brand, denomUri: string) => TransferConverter} makeTransferConverter
 */

/**
 * @typedef {Object} TransferMarshaller wire protocol manipulation functions
 * @property {(localAmount: Amount) => Bytes} marshalLocalAmount
 * @property {(data: Bytes) => Amount} unmarshalLocalAmount
 * @property {(success: boolean, error: any) => Bytes} marshalResult
 * @property {(data: Bytes) => { success: boolean, error: any }} unmarshalResult
 */
/** @type {TransferProtocol} */
const ics20v1TransferProtocol = harden({...});
const DEFAULT_TRANSFER_PROTOCOL = ics20v1TransferProtocol;
// ...
    /**
     * Return a handler that can be used with the Network API.
     * @param {TransferProtocol} [transferProtocol=ics20v1TransferProtocol] specific encoding to speak to the other side
     * @returns {ConnectionHandler}
     */
    makePegConnectionHandler(transferProtocol = ics20V1TransferProtocol) {
```

There would be other changes, to remove the old string-based `transferProtocol` from the rest of the code, and of course to use the new object.

Thanks for bringing this up!

**Comment by Tartuffo** [comment]
@michaelfig   This is in the "Up Next" pipeline, but does not have a MN-1 label.  If it is needed for MN-1, please label, otherwise move from "Up Next" to "Product Backlog".  I'm asking because I want "Up Next" to really reflect the things we plan to work on for MN-1.

**Comment by Tartuffo** [comment]
@michaelfig this needs an area label to get included in the correct weekly team meetings.  Can you please assign the appropriate one?  (Is this cosmic-swingset?)

**Comment by michaelfig** [comment]
> @michaelfig this needs an area label to get included in the correct weekly team meetings. Can you please assign the appropriate one? (Is this cosmic-swingset?)

I gave it the "pegasus" label.  It's a core Zoe contract, not specific to cosmic-swingset.

**Comment by dckc** [comment]
What's a "core Zoe contract"? According to [#1656](https://github.com/Agoric/agoric-sdk/issues/1656) , the contracts in the zoe package are examples and should move elsewhere. Should the pegasus contract move to the `run-protocol` package?

In any case, which meeting do we review **pegasus** stuff in?

**Comment by Tartuffo** [comment]
If it is a core Zoe contract, please label it "Zoe Contract", which will get reviewed in the "Zoe/ERTP" meeting.  
We don't review Pegasus in any meeting, because Pegasus was not considered needed for MN-1.

**Comment by Tartuffo** [comment]
This is done.
