### ISSUE TITLE
how to navigate using @ts-check type annotations?

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-pegasus#3]
When I ran `yarn install` (after cloning 7f3f49d) I got:

```
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
Couldn't find any versions for "@agoric/notifier" that matches "0.0.1"
? Please choose a version of "@agoric/notifier" from this list: 0.1.3
Couldn't find any versions for "@agoric/install-ses" that matches "^0.1.0"
? Please choose a version of "@agoric/install-ses" from this list: 0.2.0
Couldn't find any versions for "@agoric/notifier" that matches "0.0.1"
```

Maybe the `yarn install` convention doesn't apply to Agoric dApps? I see "Agoric's getting started documentation" among the References in the readme, but the link goes to [Agoric Documentation Guide](https://agoric.com/documentation/getting-started/) and it's not clear which part of that is relevant.

**Comment by dckc** [comment]
p.s. my motivation for looking at this was to navigate the [@ts-check](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) types in the `pegasus.js` contract in vs-code.

I'm getting a bunch of problems such as:

```
Cannot find type definition file for 'ses'.ts(2688)
Module '"../../node_modules/@agoric/assert/src/assert"' has no exported member 'q'.ts(2305)
Cannot find module '@agoric/zoe/src/contractSupport' or its corresponding type declarations.ts(2307)
Namespace '"/home/connolly/projects/agoric/dapp-pegasus/node_modules/@agoric/notifier/src/notifier"' has no exported member 'Notifier'.ts(2694)
```

**Comment by michaelfig** [comment]
`agoric install`

**Comment by dckc** [comment]
`agoric install` instead of `yarn install` seems to succeed, but the other symptoms persist: `Cannot find type definition file for 'ses'...` etc. in vs-code.

I'm actually using codium, but I'd be surprised if that matters. But to be sure: how is `tsc` supposed to be invoked? If I just invoke `./node_modules/.bin/tsc` I get a page of tsc usage stuff.

**Comment by michaelfig** [comment]
I'm afk.  Don't invoke tsc.  The ses pr is probably not yet merged, so you'll need yarn link magic against my typing patch.

**Comment by michaelfig** [comment]
I think this works now (with `agoric install`).  Closing, but feel free to reopen if there are ongoing issues.

**Comment by dckc** [comment]
yes, it works now. Thanks!
